Repository dialetus/dialetus-service, pull requests merged in 2019-02, with the labels that each got.

#71 new slang added to carioques.
  dialects/carioques.json
Labels: 🆒 Priority: Low, 🐛 Type: Patch

#72 patch: add more paulistes dialects
  dialects/paulistes.json
Labels: 🐛 Type: Patch

#75 #5 adding variations support for the dialects
  .gitignore
  dialects/potiguares.json
  lib/controllers/regions/get-one-by-region-and-slug.js
  lib/controllers/regions/list-by-region.js
  lib/helpers/dialect.js
  package.json
  test/integration/regions.js
  test/unit/lib/helpers/dialect.js
  yarn.lock
Labels: 🛠 Type: Minor
