Repository dialetus/dialetus-service, pull requests merged in 2019-10, with the labels that each got.

#130 Jaco
  dialects/paulistes.json
Labels: 🛠 Type: Minor

#132 Add synonyms field in dialect object
  dialects/carioques.json
  readme.md
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#137 Update pernambuques.json
  dialects/pernambuques.json
Labels: 🛠 Type: Minor

#136 Add some gauches dialects
  dialects/gauches.json
  test/integration/regions.js
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#134 new dialects on potiguares
  dialects/potiguares.json
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#138 Added new dialects on cearenses
  dialects/cearences.json
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#143 New dialects on catarines.json
  dialects/catarines.json
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#145 add dialects goma and descolar into paulistes
  dialects/paulistes.json
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#135 New dialects on mineires.json
  dialects/mineires.json
Labels: 🕵️ Status: PR In Review, 🛠 Type: Minor

#161 adicionando 'oxe' como dialeto pernambuques e variante de 'oxente'
  dialects/pernambuques.json
Labels: 🕵️ Status: PR In Review
