Repository dialetus/dialetus-service, pull requests merged in 2019-03, with the labels that each got.

#80 adding amazones dialect
  dialects/amazones.json
  test/integration/regions.js
Labels: 🛠 Type: Minor

#84 Piauies dialect
  README.md
  dialects/piauies.json
  test/integration/regions.js
Labels: ❓Question, 🛠 Type: Minor

#85 New dialetus gauches
  dialects/gauches.json
  test/integration/regions.js
Labels: 🐛 Type: Patch, 🕵️ Status: PR In Review

#88 Search api
  .gitignore
  README.md
  lib/controllers/search/index.js
  lib/helpers/dialect.js
  lib/helpers/string.js
  lib/routes/index.js
  lib/routes/search.js
  test/integration/search.js
  test/unit/lib/controllers/search/index.js
  test/unit/lib/helpers/dialect.js
Labels: 💡Proposal, 🕵️ Status: PR In Review
